language: node_js
node_js:
  - '10'
install:
  - rm -rf build && npm ci
env:
  - NODE_ENV=production
deploy:
  provider: releases
  api_key: ""
  file_glob: true
  file: build/sublime/*
  skip_cleanup: true
  on:
    tags: true
